name = "hono-mdx-example"
main = "src/examples/worker.ts"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]

[build.upload.format]
type = "modules"

[miniflare]
modules = true

[node_compat]
enabled = true

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
